/**
 * @file task.ts
 * @description Core type definitions for the Employee Task Management Dashboard.
 * All domain types are strictly typed — no `any` allowed downstream.
 * This is the single source of truth for all task-related shapes and constants.
 */

// ---------------------------------------------------------------------------
// Primitive union types
// ---------------------------------------------------------------------------

/**
 * The lifecycle status of a task.
 * - "Pending"     — Created but work has not started.
 * - "In Progress" — Actively being worked on.
 * - "Completed"   — Work is done and accepted.
 * - "Rejected"    — Reviewed and rejected; requires rework or closure.
 */
export type TaskStatus = "Pending" | "In Progress" | "Completed" | "Rejected";

/**
 * The urgency level of a task, used for sorting and visual indicators.
 * - "High"   — Needs immediate attention; may block other work.
 * - "Medium" — Important but not immediately blocking.
 * - "Low"    — Nice-to-have or low-urgency background work.
 */
export type TaskPriority = "Low" | "Medium" | "High";

/**
 * The field keys available for sorting the task list.
 * - "dueDate"  — Sort ascending by due date (soonest first).
 * - "priority" — Sort descending by priority weight (High > Medium > Low).
 * - "none"     — Preserve original insertion order.
 */
export type SortByKey = "dueDate" | "priority" | "none";

// ---------------------------------------------------------------------------
// Runtime constant arrays (DRY option rendering, avoids magic strings)
// ---------------------------------------------------------------------------

/** All valid task statuses as a readonly tuple, in logical lifecycle order. */
export const TASK_STATUSES: ReadonlyArray<TaskStatus> = [
  "Pending",
  "In Progress",
  "Completed",
  "Rejected",
] as const;

/** All valid task priorities as a readonly tuple, from lowest to highest urgency. */
export const TASK_PRIORITIES: ReadonlyArray<TaskPriority> = [
  "Low",
  "Medium",
  "High",
] as const;

/** All valid sort keys as a readonly tuple. */
export const SORT_KEYS: ReadonlyArray<SortByKey> = [
  "none",
  "dueDate",
  "priority",
] as const;

// ---------------------------------------------------------------------------
// Core entity
// ---------------------------------------------------------------------------

/**
 * Represents a single employee task in the system.
 * This is the canonical shape stored in Zustand and persisted to localStorage.
 */
export interface Task {
  /** Auto-incremented unique identifier. Always a positive integer. */
  id: number;

  /** Human-readable task title. Must be 3–100 characters. */
  title: string;

  /** Detailed description of what must be done. Must be 10–500 characters. */
  description: string;

  /** Current lifecycle status of the task. */
  status: TaskStatus;

  /** Urgency level of the task. */
  priority: TaskPriority;

  /** Full name of the employee the task is assigned to. */
  assignedTo: string;

  /**
   * Target completion date in ISO 8601 format (YYYY-MM-DD).
   * Stored as a string to avoid timezone serialization issues.
   */
  dueDate: string;

  /**
   * UTC ISO 8601 timestamp of when the task was created (e.g. "2026-07-02T11:00:00.000Z").
   * Set once at creation; never mutated.
   */
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Derived / utility types
// ---------------------------------------------------------------------------

/**
 * Shape used by the task creation form.
 * Excludes `id` and `createdAt` because those are generated by the store.
 */
export type TaskFormInput = Omit<Task, "id" | "createdAt">;

/**
 * Validation error messages keyed by field name.
 * A field key is present in the object only when that field has a validation error.
 * An empty object `{}` means the form is fully valid.
 *
 * @example
 * const errors: FormErrors = { title: "Title must be at least 3 characters." };
 */
export interface FormErrors {
  title?: string;
  description?: string;
  assignedTo?: string;
  dueDate?: string;
}
